#include <SDL.h>
#include <SDL_image.h>
#include <stdio.h>
#include <stdlib.h>
//#include <SDL_mixer.h>
#include "drawText.h"
#include "updateInvaders.h"
#include "Defender.h"
#include "initializeInvaders.h"
#include "drawHighscore.h"
#include "initializeHighscores.h"
#include "direction.h"
#include "selectLetter.h"
#include "insertHighscore.h"
#include "initializeBarriers.h"
#include "drawBarriers.h"
#include "writeHighscores.h"
#include "readHighscores.h"
#include "updateCollisions.h"
#include "initializeDefender.h"
#include "updateMissiles.h"
#include "drawMissiles.h"
#include "updateBarriers.h"
#include "updateDefender.h"
#include "drawInvaders.h"
